<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DesignmovesPhpSettings\Module'         => __DIR__ . '/Module.php',
  'DesignmovesPhpSettingsTest\Bootstrap'  => __DIR__ . '/test/Bootstrap.php',
  'DesignmovesPhpSettingsTest\ModuleTest' => __DIR__ . '/test/DesignmovesPhpSettingsTest/ModuleTest.php',
);
